name: deploy-book
on:
  push:
    branches:
      - main
permissions:
  pages: write
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install sphinx nbsphinx sphinx-rtd-theme sphinx-togglebutton sphinx-rtd-dark-mode sphinx-copybutton sphinx-design
          sudo apt-get install -y pandoc
      - name: Build
        run: sphinx-build -b html . _build/html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/html
      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true